name: Build App & Deploy

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: 📂 deploy
      uses: hazeezet/caprover-action@v1
      with:
        server: 'https://captain.brunonascimento.dev.br'
        app-token: ${{ secrets.APP_TOKEN }}
        app-name: ${{ secrets.APP_NAME }}
        plain: true
        branch: main